default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: datarockets-finance-app_development

test:
  <<: *default
  database: datarockets-finance-app_test

production:
  <<: *default
  database: datarockets-finance-app_production
  username: <%= ENV['DATAROCKETS_FINANCE_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['DATAROCKETS_FINANCE_APP_DATABASE_PASSWORD'] %>
