default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: datarockets-finance-app_development

test:
  <<: *default
  database: datarockets-finance-app_test

production:
  <<: *default
  database: datarockets-finance-app_production
  username: datarockets-finance-app
  password: <%= ENV['DATAROCKETS_FINANCE_APP_DATABASE_PASSWORD'] %>
