IrresponsibleModule:
  enabled: false
PrimaDonnaMethod:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
UncommunicativeMethodName:
  enabled: true
InstanceVariableAssumption:
  enabled: false
FeatureEnvy:
  exclude:
    - "ApplicationHelper"
    - "BalanceTransactions::Updater"
    - "BalanceTransactions::Creator"
    - "BalanceTransactionsController#compose_date"
    - "TransactionsHelper#categories_by_name_and_id"
DuplicateMethodCall:
  exclude:
    - "BalanceTransactionsController#compose_date"
    - "ApplicationController#form_errors"
UtilityFunction:
  exclude:
    - "ApplicationHelper"
TooManyStatements:
  max_statements: 9
TooManyInstanceVariables:
  max_instance_variables: 8
