IrresponsibleModule:
  enabled: false
PrimaDonnaMethod:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
UncommunicativeMethodName:
  enabled: true
InstanceVariableAssumption:
  enabled: false
FeatureEnvy:
  exclude:
    - "ApplicationHelper"
    - "BalanceTransactions::Updater"
    - "BalanceTransactions::Creator"
UtilityFunction:
  exclude:
    - "ApplicationHelper"
TooManyStatements:
  max_statements: 8
