IrresponsibleModule:
  enabled: false
PrimaDonnaMethod:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
UncommunicativeMethodName:
  enabled: true
  accept:
    - google_oauth2
InstanceVariableAssumption:
  enabled: false
FeatureEnvy:
  exclude:
    - "ApplicationHelper"
UtilityFunction:
  exclude:
    - "ApplicationHelper"
TooManyStatements:
  max_statements: 8
