IrresponsibleModule:
  enabled: false
PrimaDonnaMethod:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
UncommunicativeMethodName:
  enabled: false
InstanceVariableAssumption:
  enabled: false
